version: '2.1'
services:
  db:
    image: vote-db
    ports:
    - "5984:5984"
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:5984/ || exit 1"]
      interval: 10s
      timeout: 5s
  web:
    image: movie-voter
  hoodie:
    image: movie-hoodie
#   db:
#     image: mysql
#     ports:
#     - "3306:3306"
#     environment:
#     - MYSQL_ROOT_PASSWORD=password
#     - MYSQL_USER=user
#     - MYSQL_PASSWORD=password
#     - MYSQL_DATABASE=demodb